### ISSUE TITLE
TypeError: FormatCode() got an unexpected keyword argument 'verify'

### ISSUE THREAD

**Issue by yangguanghaiann** [IDEA-Research/DINO#232]
python main.py --output_dir /home/pcl/DETR/DINOout -c config/DINO/DINO_4scale.py --coco_path /home/pcl/DETR/DETRinput/ --options dn_scalar=100 embed_init_tgt=TRUE dn_label_coef=1.0 dn_bbox_coef=1.0 use_ema=False dn_box_noise_scale=1.0 --pretrain_model_path ./checkpoint0033_4scale.pth --finetune_ignore label_enc.weight class_embed
Not using distributed mode
Loading config file from config/DINO/DINO_4scale.py
Traceback (most recent call last):
  File "main.py", line 388, in <module>
    main(args)
  File "main.py", line 96, in main
    cfg.dump(save_cfg_path)
  File "/home/pcl/DETR/DETR/9DINO/DINO-main/util/slconfig.py", line 363, in dump
    f.write(self.pretty_text)
  File "/home/pcl/DETR/DETR/9DINO/DINO-main/util/slconfig.py", line 317, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
TypeError: FormatCode() got an unexpected keyword argument 'verify'

这是什么问题？如何解决？

**Comment by yangguanghaiann** [comment]
File "/home/pcl/DETR/DETR/9DINO/DINO-main/util/slconfig.py", line 317, in pretty_text
改为这样        text, _ = FormatCode(text, style_config=yapf_style)  #, verify=True

可以训练，不知道有没有问题，会不会影响训练效果？

**Comment by SWHL** [comment]
我也遇到同样问题了，看着这个只是用来规范化代码的，似乎没啥影响

**Comment by LANDDKPLA** [comment]
pip install numpy==1.23.5 yapf==0.40.1

**Comment by heitorrapela** [comment]
> pip install numpy==1.23.5 yapf==0.40.1

This versions solved the same problem for me.

**Comment by ezthor** [comment]
> pip install numpy==1.23.5 yapf==0.40.1

It works. Thanks

**Comment by llmgpt** [comment]
为什么不关掉这个issue?我也用的第一种方式.Why don't you close this issue? I did it the first way, too.
