### ISSUE TITLE
undefined symbol: _ZNK3c1010TensorImpl18compute_contiguousEv

### ISSUE THREAD

**Issue by LANDDKPLA** [IDEA-Research/DINO#233]
Failed when Compiling CUDA operators `python test.py`.
Error information is as follows
```bash
(/data/Envs/dino39) /data/DINO/models/dino/ops$ python test.py
Traceback (most recent call last):
  File "/data/DINO/models/dino/ops/test.py", line 18, in <module>
    from functions.ms_deform_attn_func import MSDeformAttnFunction, ms_deform_attn_core_pytorch
  File "/data/DINO/models/dino/ops/functions/__init__.py", line 9, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "/data/DINO/models/dino/ops/functions/ms_deform_attn_func.py", line 18, in <module>
    import MultiScaleDeformableAttention as MSDA
ImportError: /data/Envs/dino39/lib/python3.9/site-packages/MultiScaleDeformableAttention-1.0-py3.9-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl18compute_contiguousEv
```
My environment settings:
```
NVIDIA GeForce RTX 4090
cuda-11.8
python-3.9
torch==2.0.0 torchvision==1.15.1
```

The program were previously able to run `python test.py` in `2080 Ti, python-3.7, cuda-11.6` but failed to train because `cuda out of memory`. So I change to 4090 but still failed. What should I do?

**Comment by meirashaf** [comment]
You have the same problem as this issue [https://github.com/CASIA-IVA-Lab/DPT/issues/1](url). Just make sure you ran the model up until the [Compiling CUDA operators](https://github.com/fundamentalvision/Deformable-DETR/tree/main?tab=readme-ov-file#compiling-cuda-operators).
