### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by 01fe21bec239** [IDEA-Research/DINO#257]
!bash scripts/DINO_train.sh /content/sample_data/COCODIR
Not using distributed mode
Loading config file from config/DINO/DINO_4scale.py
Traceback (most recent call last):
  File "/content/DINO/DINO/DINO/main.py", line 388, in <module>
    main(args)
  File "/content/DINO/DINO/DINO/main.py", line 96, in main
    cfg.dump(save_cfg_path)
  File "/content/DINO/DINO/DINO/util/slconfig.py", line 363, in dump
    f.write(self.pretty_text)
  File "/content/DINO/DINO/DINO/util/slconfig.py", line 317, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
TypeError: FormatCode() got an unexpected keyword argument 'verify'
while running the above command on my custom data i facing this error pls resolve it(i am using colab for training)

**Comment by Ochre-amber** [comment]
pip install yapf==0.40.1
